CREATE TABLE [dbo].[UserBadge] (
    [UserBadgeID] UNIQUEIDENTIFIER CONSTRAINT [DF_UserBadge_UserBadgeID] DEFAULT (newid()) NOT NULL,
    [UserID]      UNIQUEIDENTIFIER NOT NULL,
    [BadgeID]     UNIQUEIDENTIFIER NOT NULL,
    [Date]        DATETIME2 (7)    NOT NULL,
    CONSTRAINT [PK_UserBadge] PRIMARY KEY CLUSTERED ([UserBadgeID] ASC),
    CONSTRAINT [FK_UserBadge_Badge] FOREIGN KEY ([BadgeID]) REFERENCES [dbo].[Badge] ([BadgeID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_UserBadge_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([UserID]) ON DELETE CASCADE ON UPDATE CASCADE
);



